import { type NextPage } from "next";
import { useRef } from "react";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";

const HomePage: NextPage = () => {
  const input = useRef<HTMLInputElement>(null);
  const {
    mutate: mutateShortUrl,
    data,
    isSuccess,
    error,
    isError,
  } = api.shortUrl.create.useMutation();

  return (
    <>
      <Head>
        <title>Url Shortener</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-[100lvh] flex-col items-center justify-center bg-gradient-to-b from-blue-800 to-slate-900 text-slate-200">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-4xl font-extrabold tracking-tight lg:text-6xl">
            Url Shortener
          </h1>
          <input
            ref={input}
            className="rounded bg-slate-900/75 px-3 py-2 text-slate-50 shadow outline-none"
            placeholder="https://"
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                mutateShortUrl({
                  url: input.current?.value ?? "",
                });
              }
            }}
          />
          {isSuccess && (
            <Link href={`/to/${data.slug}`} target="_blank">
              {window.location.origin}/to/{data.slug}
            </Link>
          )}
          {isError && (
            <span className="text-red-500">
              {error.data?.zodError?.fieldErrors["url"] ??
                (error.data?.code === "CONFLICT" && "URL already registered")}
            </span>
          )}
        </div>
      </main>
    </>
  );
};

export default HomePage;
